version: '3.9'

services:
  glubl-test-signal:
    image: node
    container_name: gtest-signal
    environment:
      TOKEN: "${TOKEN:?Missing TOKEN}"
      HOST: "${HOST}"
      PORT: "${PORT}"
    env_file:
      - server.env
    volumes:
      - ./server.js:/server.js
      - ./public:/public
    ports:
      - 3030:3030
    command: ["node", "/server.js"]
